### ISSUE TITLE
test.sh errors:

### ISSUE THREAD

**Issue by MyraBaba** [GunshipPenguin/kiteshield#5]
Hi,

test.sh gives:

> 
> 
> Step 1/4 : FROM centos:8
> 8: Pulling from library/centos
> a1d0c7532777: Pulling fs layer
> a1d0c7532777: Download complete
> a1d0c7532777: Pull complete
> Digest: sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177
> Status: Downloaded newer image for centos:8
>  ---> 5d0da3dc9764
> Step 2/4 : RUN yum install -y dnf-plugins-core
>  ---> Running in ae63c8a6eb08
> CentOS Linux 8 - AppStream                      160  B/s |  38  B     00:00    
> Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
> The command '/bin/sh -c yum install -y dnf-plugins-core' returned a non-zero code: 1
> -e
>

**Comment by GunshipPenguin** [comment]
Hi,

This likely has to do with CentOS 8 being EOL'd by Redhat. Seems they moved the repository URL as a result. 

https://techglimpse.com/failed-metadata-repo-appstream-centos-8/.

I haven't been working on this project for a while, but PR's are welcome if you want to fix this.

Cheers,
Rhys
